### ISSUE TITLE
NavMenu does not work with TypeScript

### ISSUE THREAD

**Issue by gabrielbull** [gabrielbull/react-desktop#63]
I separated the two issues. Reference: Issue #61 

>Also, I started writing typings for react-desktop thinking it was the reason I couldn't get [my NavMenu](https://github.com/erichiller/mkmrk/blob/master/src/menu.tsx) working, but it still didn't (called setstate() on an unmounted component) work (and my definitions are neither done nor guaranteed perfect).

Did you get it to work? Your [example converted to ES6](https://gist.github.com/gabrielbull/baac43287c19f378f89be7a45e730828) works fine

**Comment by erichiller** [comment]
No, unfortunately, I am still having the same issue. I am not sure on this one, is your gist from my typescript directly transpiled?

**Comment by gabrielbull** [comment]
I transpiled by hand to ES6.

**Comment by erichiller** [comment]
[Here I've done one I transpiled into commonjs - one into es6 -- they look proper and nearly the same](https://gist.github.com/erichiller/f603ff7ec1956324c5f1cdf67cc4e12a), but rather than maintaining the jsx syntax, it is replaced with the underlying javascript it would appear. (ala ` React.createElement( windows_1.NavPane,` for `<NavPane>`. I can not see anything off here?

**Comment by erichiller** [comment]
I figured this out on my side - it was user error - I was using it improperly, however it did cause me to write a lot more definitions for typescript - I will get these to you soon. Thanks - Eric

**Comment by gabrielbull** [comment]
Cool thanks!
